app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/jdbc_demo
      username: nenad
      password: 'password'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always


